完善其余的查询条件
shuishiyuanzhong/go-gql-builder pull request #17
Opened 2024-04-10 09:55 UTC by HaHA3507

2024-04-11 09:02 UTC, KooKouse commented on pkg/adapter/internal/argument/order_by.go
> +		sort, ok := Sort_value[strings.ToUpper(sortString)]
只是单纯的判断一下入参对不对而已

2024-04-11 09:27 UTC, HaHA3507 commented on pkg/adapter/internal/argument/order_by.go
> +func (f *OrderByArgument) CombineSql(clauses *QueryClauses) {
fiter也没有判断表中是否有这个字段

2024-04-12 06:26 UTC, KooKouse requested changes

2024-04-12 06:26 UTC, KooKouse commented on pkg/adapter/internal/argument/limit.go
> +// limit:[1,9]
这种结构用json会不会好点，然后offset就成了一个可选项
{
   count: 10
   offset : 0
}

2024-04-12 06:26 UTC, KooKouse commented on pkg/adapter/internal/argument/order_by.go
> +	Sort = map[string]struct{}{
这个结构需要被export吗？

2024-04-12 06:28 UTC, KooKouse commented on pkg/adapter/internal/argument/order_by.go
> +func (f *OrderByArgument) CombineSql(clauses *QueryClauses) {
所以看上去需要重新设计一下，或者看看filter一个不存在的字段会报什么错误

2024-04-12 07:15 UTC, HaHA3507 commented on pkg/adapter/internal/argument/order_by.go
> +func (f *OrderByArgument) CombineSql(clauses *QueryClauses) {
从mysql抛出错误来，说where语句中找不到该字段

2024-04-12 07:19 UTC, HaHA3507 commented on pkg/adapter/internal/argument/limit.go
> +// limit:[1,9]
这种结构就得判断字段存不存在，可以这样改

2024-04-12 07:25 UTC, HaHA3507 commented on pkg/adapter/internal/argument/limit.go
> +// limit:[1,9]
这点你决定一下

2024-04-12 08:00 UTC, KooKouse commented on pkg/adapter/internal/argument/limit.go
> +// limit:[1,9]
有没有可能入参处理成一个string，然后序列化到一个struct上面，这样就不需要逐个判断字段存不存在了

2024-04-12 08:01 UTC, KooKouse commented on pkg/adapter/internal/argument/order_by.go
> +func (f *OrderByArgument) CombineSql(clauses *QueryClauses) {
这样也行吧，暂时不用处理这么快

2024-04-12 08:38 UTC, HaHA3507 commented on pkg/adapter/internal/argument/limit.go
> +// limit:[1,9]
他会先断言成这个*ast.ObjectValue，你说的只能新写一个断言函数

2024-04-12 08:56 UTC, KooKouse commented on pkg/adapter/internal/argument/limit.go
> +// limit:[1,9]
对，在parseAstValue这个函数的基础上进行更精细化的处理，普通的数据类型不返回string而是它对应的数据类型，然后ObjectValue最终返回一段字符串或者[]byte的json格式的东西

2024-04-12 09:27 UTC, HaHA3507 commented on pkg/adapter/internal/argument/limit.go
> +// limit:[1,9]
fiter上面也要同时修改的喔

2024-04-12 09:54 UTC, HaHA3507 commented on pkg/adapter/internal/argument/limit.go
> +// limit:[1,9]
> 有没有可能入参处理成一个string，然后序列化到一个struct上面，这样就不需要逐个判断字段存不存在了

这样的话，有一个情况，就是零值的处理，得区分用户是传了0还是没传数据默认零值，可能struct中得引入指针

2024-04-12 10:26 UTC, KooKouse commented on pkg/adapter/internal/argument/limit.go
> +// limit:[1,9]
整个改动可能会变复杂，可以先推演一下看看会不会有别的坑。

0值的问题如果是Limit这个场景的话，倒没什么问题，偏移量传0和不传没有差别。

2024-04-13 05:29 UTC, HaHA3507 commented on pkg/adapter/internal/argument/limit.go
> +// limit:[1,9]
fiter上面如果用struct来匹配所有的operation反而做复杂了

2024-04-15 04:41 UTC, KooKouse commented on pkg/adapter/internal/argument/limit.go
> +// limit:[1,9]
> 这种结构用json会不会好点，然后offset就成了一个可选项 { count: 10 offset : 0 }

用这种结构吧，0值的情况只针对count字段，如果count为零则直接报错就行了，offset为零就当作用户没有传值

2024-04-16 02:17 UTC, KooKouse approved these changes

2024-04-16 02:21 UTC, merged